version: '3.8'
services:
  db:
    image: postgres:13
    container_name: team_formation_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: team_formation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d team_formation"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: