# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters

[environments.local]
url = "jdbc:postgresql://127.0.0.1:15432/"
user = "postgres"
schemas = ["sample"]

[flyway]
locations = ["filesystem:./migrations/"]
cleanDisabled = true
validateMigrationNaming=true
reportEnabled = true
table = "FlywayHistory"
baselineVersion = "2021.11.000"
baselineDescription = "Baseline before converting to flyway migrations"

